### ISSUE TITLE
I tried with this script also, only single nproc seems to be working. Do i need to define any additional enviornment variables like RANK or LocaL HOST

### ISSUE THREAD

**Issue by arpitsahni04** [yoshitomo-matsubara/torchdistill#379] opened 2023-07-26 03:42 UTC
I tried with this script also, only single nproc seems to be working. Do i need to define any additional enviornment variables like RANK or LocaL HOST

![image](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/fe11aa41-c82f-474f-a8dd-987321646887)

also can we enable --amp in torchdistill. the img/s on imagenet is also pretty good on the original script: https://github.com/pytorch/vision/blob/main/references/classification/train.py
what can i do differently to get img/s higher (I'm getting like 12 img/s :( )and multi gpu run working 

![image](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/2e4e92b7-3cf1-4fb2-a36d-162e272a36ac)
please help

_Originally posted by @arpitsahni04 in https://github.com/yoshitomo-matsubara/torchdistill/discussions/378#discussioncomment-6544424_

Can you please tell why the dataloading img/s speed is much lesser in torchdistill as compared to the train.py file in torchvision for the same dataset??
Screenshot 2023-07-25 at 11.41.02 PM

![Screenshot 2023-07-25 at 11 41 02 PM](https://github.com/yoshitomo-matsubara/torchdistill/assets/81643693/af35f892-dd7d-4970-af36-726f2645cf98)

**Comment by yoshitomo-matsubara** [comment] 2023-07-26 03:53
Closing because this is a duplicate discussion https://github.com/yoshitomo-matsubara/torchdistill/discussions/378 and the interactions in the discussion show that the DDP did not work even with train.py in torchvision for image classification, and the problem is not directly caused by torchdistill,

**Closed by yoshitomo-matsubara** 2023-07-26 03:53 UTC
