### ISSUE TITLE
About the application scenarios supported by the program

### ISSUE THREAD

**Issue by KOOKOKOK** [yoshitomo-matsubara/torchdistill#462] opened 2024-04-24 02:10 UTC
Hi, I would like to know if all the reproduced paper methods in this project support semantic segmentation, categorization, and target detection, or is it just the original paper that corresponds to the work. For example, if the original paper is doing knowledge distillation about target detection, then the pages in the project only support target detection.

**Comment by yoshitomo-matsubara** [comment] 2024-04-24 15:27
Please read https://github.com/yoshitomo-matsubara/torchdistill#issues--questions--requests and use [Discussions](https://github.com/yoshitomo-matsubara/torchdistill/discussions) instead

Closing this as it's not a bug.

**Closed by yoshitomo-matsubara** 2024-04-24 15:27 UTC
