### ISSUE TITLE
Knowledge distillation related

### ISSUE THREAD

**Issue by andynnnnn** [yoshitomo-matsubara/torchdistill#476] opened 2024-07-03 09:41 UTC
Hello, it's great to see your achievements. I've been working with large CV models similar to Yolo-world and Grounding Dino, training them on my own dataset to obtain pre-trained files. I'd like to know how I can derive pre-trained files with relatively smaller model parameters while still retaining the Zero-Shot detection capability of the models.

**Comment by yoshitomo-matsubara** [comment] 2024-07-03 15:44
Please read https://github.com/yoshitomo-matsubara/torchdistill#issues--questions--requests and use [Discussions](https://github.com/yoshitomo-matsubara/torchdistill/discussions) instead

Closing this as it's not a bug.

**Closed by yoshitomo-matsubara** 2024-07-03 15:44 UTC
