### ISSUE TITLE
is tochdistill support knowlede distillation for Vision Foundation Models like Grounding Dino / Grounding DinoSAM ?

### ISSUE THREAD

**Issue by solomonmanuelraj** [yoshitomo-matsubara/torchdistill#427] opened 2023-11-17 14:56 UTC
Hi Team,

Currently i am working in Grounding Dino vision foundation model for object detection ( https://github.com/IDEA-Research/GroundingDINO). The model size is around 660 MB. I want to deploy it in the edge device and i like to use Grounding Dino model (as teacher model) for KD. 

I want to know whether torchdistill package supports vision foundation model ?
if it is so i want to know is there any sample link / demo code available for Vision foundation model KD.

thanks for your help.

**Comment by yoshitomo-matsubara** [comment] 2023-11-17 20:44
Please read https://github.com/yoshitomo-matsubara/torchdistill#issues--questions--requests and use Discussions instead

Closing this as it's not a bug.

**Closed by yoshitomo-matsubara** 2023-11-17 20:44 UTC
